version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - |
        bash -lc "set -euo pipefail
        # Defaults for env if not provided by CodeBuild
        export AWS_REGION=\"${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}\"
        export PROJECT_NAME=\"${PROJECT_NAME:-lawprotect365}\"
        export ENV=\"${ENV:-stg}\"
        export CODE_BUCKET=\"${CODE_BUCKET:-lawprotect-code}\"
        export LAYER_NAME=\"${LAYER_NAME:-lawprotect365-shared-ts-layer-stg}\"
        export OUTBOX_FUNCTION_NAME=\"${OUTBOX_FUNCTION_NAME:-lawprotect365-outbox-stream-handler-stg-stg}\"
        export OUTBOX_ALIAS_NAME=\"${OUTBOX_ALIAS_NAME:-live}\""
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Building @lawprotect/shared-ts'
        cd \"$CODEBUILD_SRC_DIR/packages/shared-ts\"
        npm ci
        DATABASE_URL=\"${DATABASE_URL:-postgresql://user:pass@localhost:5432/postgres?schema=public}\" npx -y prisma@5.22.0 generate
        npm run build
        npm prune --omit=dev

        echo '[INFO] Assembling layer under /tmp/layer'
        LAYER_DIR=/tmp/layer/nodejs/node_modules/@lawprotect/shared-ts
        mkdir -p \"$LAYER_DIR/dist\"
        cp -a dist/. \"$LAYER_DIR/dist/\"
        cat > \"$LAYER_DIR/package.json\" << 'EOF'
        {
          "name": "@lawprotect/shared-ts",
          "version": "0.1.0",
          "type": "module",
          "main": "dist/cjs/index.js",
          "module": "dist/esm/index.js",
          "types": "dist/types/index.d.ts",
          "exports": {
            ".": {
              "require": "./dist/cjs/index.js",
              "import": "./dist/esm/index.js",
              "types": "./dist/types/index.d.ts"
            }
          }
        }
        EOF
        # Include Prisma in shared layer when available
        mkdir -p /tmp/layer/nodejs/node_modules/@prisma /tmp/layer/nodejs/node_modules/.prisma
        if [ -d \"$CODEBUILD_SRC_DIR/node_modules/@prisma/client\" ]; then
          cp -a \"$CODEBUILD_SRC_DIR/node_modules/@prisma/client\" /tmp/layer/nodejs/node_modules/@prisma/
        fi
        if [ -d \"$CODEBUILD_SRC_DIR/node_modules/.prisma/client\" ]; then
          cp -a \"$CODEBUILD_SRC_DIR/node_modules/.prisma/client\" /tmp/layer/nodejs/node_modules/.prisma/
        fi"

  build:
    commands:
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Packaging & uploading shared-ts layer'
        cd /tmp/layer
        zip -r shared-ts-layer.zip .
        aws s3 cp shared-ts-layer.zip \"s3://$CODE_BUCKET/shared-ts-layer.zip\""
      - |
        bash -lc "set -euo pipefail
        LAYER_NAME=\"${LAYER_NAME:-${PROJECT_NAME}-shared-ts-layer-${ENV}}\"
        if [ -z \"$LAYER_NAME\" ]; then echo '[ERROR] LAYER_NAME unresolved' >&2; exit 1; fi
        echo \"[INFO] Publishing Lambda layer: $LAYER_NAME\" 
        if ! PUBLISHED_ARN=$(aws lambda publish-layer-version \
          --region \"$AWS_REGION\" \
          --layer-name \"$LAYER_NAME\" \
          --content S3Bucket=\"$CODE_BUCKET\",S3Key=\"shared-ts-layer.zip\" \
          --compatible-runtimes nodejs20.x \
          --query LayerVersionArn --output text 2>publish-shared-ts.err); then
          echo \"[ERROR] Failed to publish $LAYER_NAME\" >&2
          cat publish-shared-ts.err >&2 || true
          exit 1
        fi
        if [ -z \"$PUBLISHED_ARN\" ] || [ \"$PUBLISHED_ARN\" = \"None\" ]; then
          echo \"[ERROR] Empty ARN after publish for $LAYER_NAME\" >&2
          cat publish-shared-ts.err >&2 || true
          exit 1
        fi
        echo \"[INFO] Shared layer ARN: $PUBLISHED_ARN\"
        echo -n \"$PUBLISHED_ARN\" > /tmp/SHARED_TS_LAYER_ARN"
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Packaging outbox-stream-handler function'
        cd \"$CODEBUILD_SRC_DIR\"
        mkdir -p outbox-stream-handler
        if [ -f \"/tmp/layer/nodejs/node_modules/@lawprotect/shared-ts/dist/lambdas/OutboxStreamHandler.js\" ]; then
          cp /tmp/layer/nodejs/node_modules/@lawprotect/shared-ts/dist/lambdas/OutboxStreamHandler.js outbox-stream-handler/index.js
        else
          echo 'const { outboxStreamHandler } = require(\"@lawprotect/shared-ts\");' > outbox-stream-handler/index.js
          echo 'exports.handler = outboxStreamHandler;' >> outbox-stream-handler/index.js
        fi
        echo '{ "type": "commonjs" }' > outbox-stream-handler/package.json
        (cd outbox-stream-handler && zip -r ../outbox-stream-handler.zip .)
        rm -rf outbox-stream-handler"
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Updating outbox Lambda with new code & shared layer'
        FUNCTION_NAME=\"${OUTBOX_FUNCTION_NAME:-${PROJECT_NAME}-outbox-stream-handler-${ENV}}\"
        ALIAS_NAME=\"${OUTBOX_ALIAS_NAME:-live}\"
        SHARED_TS_LAYER_ARN=$(cat /tmp/SHARED_TS_LAYER_ARN)
        if [ -z \"$FUNCTION_NAME\" ]; then echo '[ERROR] OUTBOX_FUNCTION_NAME is empty' >&2; exit 1; fi
        aws s3 cp outbox-stream-handler.zip \"s3://$CODE_BUCKET/outbox-stream-handler.zip\"
        aws lambda update-function-code --function-name \"$FUNCTION_NAME\" --s3-bucket \"$CODE_BUCKET\" --s3-key \"outbox-stream-handler.zip\"
        aws lambda wait function-updated --function-name \"$FUNCTION_NAME\"
        aws lambda update-function-configuration --function-name \"$FUNCTION_NAME\" --layers \"$SHARED_TS_LAYER_ARN\"
        aws lambda wait function-updated --function-name \"$FUNCTION_NAME\""
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Sanity invoking outbox to detect ImportModuleError'
        FUNCTION_NAME=\"${OUTBOX_FUNCTION_NAME:-${PROJECT_NAME}-outbox-stream-handler-${ENV}}\"
        ERR=$(aws lambda invoke --function-name \"$FUNCTION_NAME\" --payload '{}' /tmp/invoke.json --query FunctionError --output text 2>/dev/null || true)
        if [ -n \"$ERR\" ] && [ \"$ERR\" != \"None\" ]; then
          echo \"[ERROR] Lambda invocation failed (FunctionError=$ERR). Check import errors.\" >&2
          cat /tmp/invoke.json >&2 || true
          exit 1
        fi
        echo '[INFO] Invocation OK'"
      - |
        bash -lc "set -euo pipefail
        echo '[INFO] Publishing version and updating alias'
        FUNCTION_NAME=\"${OUTBOX_FUNCTION_NAME:-${PROJECT_NAME}-outbox-stream-handler-${ENV}}\"
        ALIAS_NAME=\"${OUTBOX_ALIAS_NAME:-live}\"
        CURRENT_BEFORE=$(aws lambda get-alias --function-name \"$FUNCTION_NAME\" --name \"$ALIAS_NAME\" --query FunctionVersion --output text 2>/dev/null || true)
        TARGET_VERSION=$(aws lambda publish-version --function-name \"$FUNCTION_NAME\" --description \"Build-$(date +%s)\" --query Version --output text)
        if aws lambda get-alias --function-name \"$FUNCTION_NAME\" --name \"$ALIAS_NAME\" >/dev/null 2>&1; then
          aws lambda update-alias --function-name \"$FUNCTION_NAME\" --name \"$ALIAS_NAME\" --function-version \"$TARGET_VERSION\"
        else
          aws lambda create-alias --function-name \"$FUNCTION_NAME\" --name \"$ALIAS_NAME\" --function-version \"$TARGET_VERSION\"
        fi
        CURRENT_SAFE=${CURRENT_BEFORE:-$TARGET_VERSION}
        printf \"%s\\n\" \\
          \"version: 0.0\" \
          \"Resources:\" \
          \"  - OutboxHandler:\" \
          \"      Type: AWS::Lambda::Function\" \
          \"      Properties:\" \
          \"        Name: \\\"$FUNCTION_NAME\\"\" \
          \"        Alias: \\\"$ALIAS_NAME\\"\" \
          \"        CurrentVersion: $CURRENT_SAFE\" \
          \"        TargetVersion: $TARGET_VERSION\" \
          > \"$CODEBUILD_SRC_DIR/appspec.yml\""

artifacts:
  files:
    - 'outbox-stream-handler.zip'
    - 'appspec.yml'
  discard-paths: yes
