version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version: $(node -v)"
      - echo "npm version: $(npm -v)"
      
  pre_build:
    commands:
      - echo "Building shared-ts layer..."
      - cd packages/shared-ts
      - npm ci
      - npm run build
      - npm prune --omit=dev
      
  build:
    commands:
      - mkdir -p shared-ts-layer/nodejs
      - cp -r packages/shared-ts/dist shared-ts-layer/nodejs/@lawprotect/shared-ts
      - cp -r packages/shared-ts/node_modules shared-ts-layer/nodejs/
      - cd shared-ts-layer && zip -r ../shared-ts-layer.zip . && cd ..
      - mkdir -p outbox-stream-handler
      - cp -r packages/shared-ts/dist/lambdas/* outbox-stream-handler/
      - cp packages/shared-ts/package.json outbox-stream-handler/
      - cd outbox-stream-handler && zip -r ../outbox-stream-handler.zip . && cd ..

artifacts:
  files:
    - shared-ts-layer.zip
    - outbox-stream-handler.zip
