version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - 'bash -lc "set -euo pipefail; echo Using Node: $(node -v); echo Using npm: $(npm -v)"'

  pre_build:
    commands:
      - |
        bash -lc "set -euo pipefail
        echo '>>> Building shared-ts layer...'
        test -d \"$CODEBUILD_SRC_DIR/packages/shared-ts\" || { echo 'shared-ts not found'; exit 2; }
        cd \"$CODEBUILD_SRC_DIR/packages/shared-ts\"
        npm ci
        DATABASE_URL=\"\${DATABASE_URL:-postgresql://user:pass@localhost:5432/postgres?schema=public}\" npx -y prisma@5.16.1 generate
        npm run build
        npm prune --omit=dev
        mkdir -p /tmp/layer/nodejs
        cp -a dist /tmp/layer/nodejs/
        cp package.json /tmp/layer/nodejs/
        if [ -d \"$CODEBUILD_SRC_DIR/node_modules\" ]; then
          mkdir -p /tmp/layer/nodejs/node_modules
          cp -a \"$CODEBUILD_SRC_DIR/node_modules/.\" /tmp/layer/nodejs/node_modules/
        else
          echo 'root node_modules not found'
          exit 2
        fi"

  build:
    commands:
      - |
        bash -lc "set -euo pipefail
        cd /tmp/layer
        zip -r shared-ts-layer.zip .
        aws s3 cp shared-ts-layer.zip \"s3://$CODE_BUCKET/shared-ts-layer.zip\""
      - |
        bash -lc "set -euo pipefail
        cd \"$CODEBUILD_SRC_DIR\"
        mkdir -p outbox-stream-handler
        if [ -f \"/tmp/layer/nodejs/dist/lambdas/OutboxStreamHandler.js\" ]; then
          cp /tmp/layer/nodejs/dist/lambdas/OutboxStreamHandler.js outbox-stream-handler/
        else
          echo 'const { outboxStreamHandler } = require(\"@lawprotect/shared-ts\");' > outbox-stream-handler/index.js
          echo 'exports.handler = outboxStreamHandler;' >> outbox-stream-handler/index.js
        fi
        cp /tmp/layer/nodejs/package.json outbox-stream-handler/
        (cd outbox-stream-handler && zip -r ../outbox-stream-handler.zip .)
        rm -rf outbox-stream-handler"
      - |
        set +e
        L_ERR=0
        FUNCTION_NAME="${OUTBOX_FUNCTION_NAME}"
        ALIAS_NAME="${OUTBOX_ALIAS_NAME}"
        if [ -z "$FUNCTION_NAME" ] || [ -z "$ALIAS_NAME" ]; then
          L_ERR=1
        fi
        aws s3 cp outbox-stream-handler.zip "s3://$CODE_BUCKET/outbox-stream-handler.zip" || L_ERR=1
        if [ "$L_ERR" -eq 0 ]; then
          aws lambda update-function-code --function-name "$FUNCTION_NAME" --s3-bucket "$CODE_BUCKET" --s3-key "outbox-stream-handler.zip" >/dev/null || L_ERR=1
        fi
        if [ "$L_ERR" -eq 0 ]; then
          echo ">>> DEBUG: Asociando layer shared-ts a la función Lambda..."
          LAYER_ARN="${SHARED_TS_LAYER_ARN}"
          echo ">>> DEBUG: SHARED_TS_LAYER_ARN=$LAYER_ARN"
          if [ -n "$LAYER_ARN" ]; then
            echo ">>> DEBUG: Ejecutando update-function-configuration..."
            aws lambda update-function-configuration --function-name "$FUNCTION_NAME" --layers "$LAYER_ARN" >/dev/null || L_ERR=1
            if [ "$L_ERR" -eq 0 ]; then
              echo ">>> DEBUG: Layer asociado exitosamente: $LAYER_ARN"
            else
              echo ">>> DEBUG: ERROR - Falló update-function-configuration"
            fi
          else
            echo ">>> DEBUG: ERROR - SHARED_TS_LAYER_ARN no está definido"
            L_ERR=1
          fi
        else
          echo ">>> DEBUG: Saltando asociación de layer - L_ERR=$L_ERR"
        fi
        if [ "$L_ERR" -eq 0 ]; then
          echo ">>> DEBUG: Esperando que la función se actualice..."
          aws lambda wait function-updated --function-name "$FUNCTION_NAME" || L_ERR=1
          if [ "$L_ERR" -eq 0 ]; then
            echo ">>> DEBUG: Función actualizada exitosamente"
          else
            echo ">>> DEBUG: ERROR - Falló wait function-updated"
          fi
        else
          echo ">>> DEBUG: Saltando wait function-updated - L_ERR=$L_ERR"
        fi
        if [ "$L_ERR" -eq 0 ]; then
          echo ">>> DEBUG: Publicando nueva versión..."
          TARGET_VERSION=$(aws lambda publish-version --function-name "$FUNCTION_NAME" --query Version --output text 2>/dev/null)
          echo ">>> DEBUG: TARGET_VERSION=$TARGET_VERSION"
          if [ -z "$TARGET_VERSION" ] || [ "$TARGET_VERSION" = "null" ]; then
            echo ">>> DEBUG: ERROR - TARGET_VERSION es nulo o vacío"
            L_ERR=1
          else
            echo ">>> DEBUG: Versión publicada exitosamente: $TARGET_VERSION"
          fi
        else
          echo ">>> DEBUG: Saltando publish-version - L_ERR=$L_ERR"
        fi
        if [ "$L_ERR" -eq 0 ]; then
          # Obtener la versión actual del ALIAS (no de la función)
          CURRENT_VERSION=$(aws lambda get-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" --query FunctionVersion --output text 2>/dev/null)
          if [ -z "$CURRENT_VERSION" ] || [ "$CURRENT_VERSION" = "null" ] || [ "$CURRENT_VERSION" = "\$LATEST" ]; then
            echo ">>> DEBUG: Alias no existe o es \$LATEST, creando alias con versión $TARGET_VERSION"
            aws lambda create-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" --function-version "$TARGET_VERSION" >/dev/null || L_ERR=1
            CURRENT_VERSION="$TARGET_VERSION"
          fi
          echo ">>> DEBUG: CURRENT_VERSION from alias: $CURRENT_VERSION"
        fi
        # Asegurar que las versiones sean enteros válidos
        CURRENT_VERSION_INT=${CURRENT_VERSION:-1}
        TARGET_VERSION_INT=${TARGET_VERSION:-1}
        echo ">>> DEBUG: CURRENT_VERSION_INT=$CURRENT_VERSION_INT, TARGET_VERSION_INT=$TARGET_VERSION_INT"
        printf "%s\n" \
          "version: 0.0" \
          "Resources:" \
          "  - OutboxHandler:" \
          "      Type: AWS::Lambda::Function" \
          "      Properties:" \
          "        Name: \"$FUNCTION_NAME\"" \
          "        Alias: \"$ALIAS_NAME\"" \
          "        CurrentVersion: $CURRENT_VERSION_INT" \
          "        TargetVersion: $TARGET_VERSION_INT" \
          > "$CODEBUILD_SRC_DIR/appspec.yml"
        echo ">>> DEBUG: AppSpec generado:"
        cat "$CODEBUILD_SRC_DIR/appspec.yml"
        echo ">>> DEBUG: Estado final - L_ERR=$L_ERR"
        if [ "$L_ERR" -ne 0 ]; then
          echo ">>> DEBUG: ERROR FINAL - Saliendo con código 1"
          exit 1
        else
          echo ">>> DEBUG: ÉXITO - Build completado sin errores"
        fi
        set -e

artifacts:
  files:
    - 'outbox-stream-handler.zip'
    - 'appspec.yml'
  discard-paths: yes
