version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Using Node: $(node -v)"
      - echo "Using npm:  $(npm -v)"

  pre_build:
    commands:
      - echo "Building shared-ts layer..."
      - cd packages/shared-ts
      - npm ci
      - npm run build
      - npm prune --omit=dev
      - cd -


      - rm -rf /tmp/layer && mkdir -p /tmp/layer/nodejs
      - cp -R packages/shared-ts/dist /tmp/layer/nodejs/
      - cp -R packages/shared-ts/node_modules /tmp/layer/nodejs/
      - cp packages/shared-ts/package.json /tmp/layer/nodejs/
      - cp packages/shared-ts/package-lock.json /tmp/layer/nodejs/

  build:
    commands:
      - cd /tmp/layer
      - zip -r shared-ts-layer.zip .
      - 'if [ -z "${CODE_BUCKET:-}" ]; then echo "ERROR: CODE_BUCKET env var is not set"; exit 1; fi'
      - aws s3 cp shared-ts-layer.zip s3://$CODE_BUCKET/shared-ts-layer.zip
      - echo "Uploaded layer to s3://$CODE_BUCKET/shared-ts-layer.zip"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
