/**
 * @fileoverview Auth Error Codes - Domain-specific error codes for auth service
 * @summary Error codes for auth service domain operations
 * @description These codes complement the shared ErrorCodes catalog. Use them to keep
 * domain failures stable and machine-readable across logs, metrics and clients.
 */

import type { ErrorCode as SharedErrorCode } from "@lawprotect/shared-ts";

/**
 * Canonical error codes for the auth domain.
 *
 * Keep codes stable once released; treat them as part of the public contract.
 */
export const AuthErrorCodes = {
  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_INVALID_STATE: "USER_INVALID_STATE",
  USER_ALREADY_ACTIVE: "USER_ALREADY_ACTIVE",
  USER_ALREADY_SUSPENDED: "USER_ALREADY_SUSPENDED",
  USER_ALREADY_DELETED: "USER_ALREADY_DELETED",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USER_ACCESS_DENIED: "USER_ACCESS_DENIED",
  USER_LIFECYCLE_VIOLATION: "USER_LIFECYCLE_VIOLATION",

  // Authentication
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Authorization
  AUTHORIZATION_FAILED: "AUTHORIZATION_FAILED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  ROLE_ASSIGNMENT_FAILED: "ROLE_ASSIGNMENT_FAILED",
  ROLE_REMOVAL_FAILED: "ROLE_REMOVAL_FAILED",
  INVALID_ROLE_ASSIGNMENT: "INVALID_ROLE_ASSIGNMENT",
  ROLE_ASSIGNMENT_CONFLICT: "ROLE_ASSIGNMENT_CONFLICT",

  // MFA
  MFA_REQUIRED: "MFA_REQUIRED",
  MFA_NOT_ENABLED: "MFA_NOT_ENABLED",
  MFA_ALREADY_ENABLED: "MFA_ALREADY_ENABLED",
  MFA_ALREADY_DISABLED: "MFA_ALREADY_DISABLED",
  MFA_VERIFICATION_FAILED: "MFA_VERIFICATION_FAILED",
  MFA_POLICY_VIOLATION: "MFA_POLICY_VIOLATION",
  INVALID_MFA_CONFIGURATION: "INVALID_MFA_CONFIGURATION",

  // OAuth
  OAUTH_PROVIDER_NOT_SUPPORTED: "OAUTH_PROVIDER_NOT_SUPPORTED",
  OAUTH_ACCOUNT_NOT_FOUND: "OAUTH_ACCOUNT_NOT_FOUND",
  OAUTH_ACCOUNT_ALREADY_LINKED: "OAUTH_ACCOUNT_ALREADY_LINKED",
  OAUTH_ACCOUNT_LINKING_FAILED: "OAUTH_ACCOUNT_LINKING_FAILED",
  OAUTH_ACCOUNT_UNLINKING_FAILED: "OAUTH_ACCOUNT_UNLINKING_FAILED",
  OAUTH_LOGIN_FAILED: "OAUTH_LOGIN_FAILED",

  // Cognito
  COGNITO_USER_NOT_FOUND: "COGNITO_USER_NOT_FOUND",
  COGNITO_USER_CREATION_FAILED: "COGNITO_USER_CREATION_FAILED",
  COGNITO_USER_UPDATE_FAILED: "COGNITO_USER_UPDATE_FAILED",
  COGNITO_USER_DELETE_FAILED: "COGNITO_USER_DELETE_FAILED",
  INVALID_COGNITO_SUB: "INVALID_COGNITO_SUB",
  COGNITO_ATTRIBUTE_UPDATE_FAILED: "COGNITO_ATTRIBUTE_UPDATE_FAILED",

  // Audit
  AUDIT_EVENT_CREATION_FAILED: "AUDIT_EVENT_CREATION_FAILED",
  AUDIT_EVENT_NOT_FOUND: "AUDIT_EVENT_NOT_FOUND",
  AUDIT_TRAIL_INCOMPLETE: "AUDIT_TRAIL_INCOMPLETE",

  // Security
  SECURITY_VIOLATION: "SECURITY_VIOLATION",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  IP_ADDRESS_BLOCKED: "IP_ADDRESS_BLOCKED",
  USER_AGENT_BLOCKED: "USER_AGENT_BLOCKED",

  // Validation
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
  INVALID_NAME_FORMAT: "INVALID_NAME_FORMAT",
  INVALID_USER_DATA: "INVALID_USER_DATA",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // Repository & Data
  REPOSITORY_ERROR: "REPOSITORY_ERROR",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  DATA_INTEGRITY_VIOLATION: "DATA_INTEGRITY_VIOLATION"
} as const;

/** Union of auth-service specific code strings. */
export type AuthErrorCode = keyof typeof AuthErrorCodes;

/**
 * Union of any error code this service can emit:
 * - Shared catalog from @lawprotect/shared-ts
 * - Auth-service specific codes above
 */
export type AnyErrorCode = SharedErrorCode | AuthErrorCode;
