/**
 * @fileoverview Signature Error Codes - Domain-specific error codes for signature service
 * @summary Error codes for signature service domain operations
 * @description These codes complement the shared ErrorCodes catalog. Use them to keep
 * domain failures stable and machine-readable across logs, metrics and clients.
 */

import type { ErrorCode as SharedErrorCode } from "@lawprotect/shared-ts";

/**
 * Canonical error codes for the signature domain.
 *
 * Keep codes stable once released; treat them as part of the public contract.
 */
export const SignatureErrorCodes = {
  // Envelopes
  ENVELOPE_NOT_FOUND: "ENVELOPE_NOT_FOUND",
  ENVELOPE_ALREADY_SENT: "ENVELOPE_ALREADY_SENT",
  ENVELOPE_INVALID_STATE: "ENVELOPE_INVALID_STATE",
  ENVELOPE_EXPIRED: "ENVELOPE_EXPIRED",
  ENVELOPE_COMPLETED: "ENVELOPE_COMPLETED",
  ENVELOPE_DECLINED: "ENVELOPE_DECLINED",
  ENVELOPE_LIMIT_EXCEEDED: "ENVELOPE_LIMIT_EXCEEDED",
  ENVELOPE_TITLE_DUPLICATE: "ENVELOPE_TITLE_DUPLICATE",
  ENVELOPE_EXPIRATION_INVALID: "ENVELOPE_EXPIRATION_INVALID",
  ENVELOPE_DOCUMENT_NOT_FOUND: "ENVELOPE_DOCUMENT_NOT_FOUND",

  // Signers
  SIGNER_NOT_FOUND: "SIGNER_NOT_FOUND",
  SIGNER_ALREADY_SIGNED: "SIGNER_ALREADY_SIGNED",
  SIGNER_ALREADY_DECLINED: "SIGNER_ALREADY_DECLINED",
  SIGNER_INVALID_STATE: "SIGNER_INVALID_STATE",
  SIGNER_EMAIL_REQUIRED: "SIGNER_EMAIL_REQUIRED",
  SIGNER_EMAIL_DUPLICATE: "SIGNER_EMAIL_DUPLICATE",
  SIGNER_CANNOT_BE_REMOVED: "SIGNER_CANNOT_BE_REMOVED",

  // Signatures
  SIGNATURE_NOT_FOUND: "SIGNATURE_NOT_FOUND",
  SIGNATURE_FAILED: "SIGNATURE_FAILED",
  SIGNATURE_HASH_MISMATCH: "SIGNATURE_HASH_MISMATCH",
  SIGNATURE_ALREADY_EXISTS: "SIGNATURE_ALREADY_EXISTS",

  // KMS / Crypto
  KMS_KEY_NOT_FOUND: "KMS_KEY_NOT_FOUND",
  KMS_PERMISSION_DENIED: "KMS_PERMISSION_DENIED",
  KMS_SIGNING_FAILED: "KMS_SIGNING_FAILED",
  KMS_VALIDATION_FAILED: "KMS_VALIDATION_FAILED",

  // Consent & Authentication
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  CONSENT_NOT_GIVEN: "CONSENT_NOT_GIVEN",
  CONSENT_NOT_FOUND: "CONSENT_NOT_FOUND",
  CONSENT_INVALID: "CONSENT_INVALID",
  CONSENT_TIMESTAMP_REQUIRED: "CONSENT_TIMESTAMP_REQUIRED",
  CONSENT_TEXT_REQUIRED: "CONSENT_TEXT_REQUIRED",
  CONSENT_IP_REQUIRED: "CONSENT_IP_REQUIRED",
  CONSENT_USER_AGENT_REQUIRED: "CONSENT_USER_AGENT_REQUIRED",
  INVITATION_TOKEN_INVALID: "INVITATION_TOKEN_INVALID",
  INVITATION_TOKEN_EXPIRED: "INVITATION_TOKEN_EXPIRED",

  // Document Service Integration
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_NOT_READY: "DOCUMENT_NOT_READY",
  DOCUMENT_INVALID_HASH: "DOCUMENT_INVALID_HASH",
  DOCUMENT_S3_ERROR: "DOCUMENT_S3_ERROR",

  // Audit & Compliance
  AUDIT_EVENT_FAILED: "AUDIT_EVENT_FAILED",
  AUDIT_TRAIL_NOT_FOUND: "AUDIT_TRAIL_NOT_FOUND",

  // Rate limits (domain-scoped; transport still uses 429)
  RATE_LIMIT_ENVELOPE_SEND: "RATE_LIMIT_ENVELOPE_SEND",
  RATE_LIMIT_SIGNER_INVITE: "RATE_LIMIT_SIGNER_INVITE",
  RATE_LIMIT_SIGNATURE_ATTEMPT: "RATE_LIMIT_SIGNATURE_ATTEMPT",

  // Security & Access Control
  ACCESS_DENIED: "ACCESS_DENIED",
  IP_ADDRESS_BLOCKED: "IP_ADDRESS_BLOCKED",
  USER_AGENT_BLOCKED: "USER_AGENT_BLOCKED",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
  GEOLOCATION_BLOCKED: "GEOLOCATION_BLOCKED",
  DEVICE_NOT_TRUSTED: "DEVICE_NOT_TRUSTED",

  // Compliance errors
  COMPLIANCE_VIOLATION: "COMPLIANCE_VIOLATION",
  AUDIT_TRAIL_INCOMPLETE: "AUDIT_TRAIL_INCOMPLETE",
  DOCUMENT_INTEGRITY_VIOLATION: "DOCUMENT_INTEGRITY_VIOLATION",
  SIGNATURE_INVALID: "SIGNATURE_INVALID",

  // Workflow
  WORKFLOW_VIOLATION: "WORKFLOW_VIOLATION",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  INVALID_SIGNING_ORDER: "INVALID_SIGNING_ORDER",
  EVENT_GENERATION_FAILED: "EVENT_GENERATION_FAILED"
} as const;

/** Union of signature-service specific code strings. */
export type SignatureErrorCode = keyof typeof SignatureErrorCodes;

/**
 * Union of any error code this service can emit:
 * - Shared catalog from @lawprotect365/shared/errors
 * - Signature-service specific codes above
 */
export type AnyErrorCode = SharedErrorCode | SignatureErrorCode;
