/**
 * @fileoverview NotificationRepository - Repository interface for Notification operations
 * @summary Defines the contract for Notification data access operations
 * @description This interface defines all data access operations for Notification entities,
 * following the repository pattern. Implementations should provide persistence operations
 * for notifications including CRUD, querying, and idempotency checks.
 */

import type { NotificationSpec } from '../notification';
import type { Page } from '@lawprotect/shared-ts';
import type { Notification } from '../../entities/Notification';
import type { NotificationId } from '../../value-objects/NotificationId';

export interface NotificationRepository {
  /**
   * @description Finds a notification by its ID
   * @param {NotificationId} id - Notification ID
   * @returns {Promise<Notification | null>} Notification entity or null if not found
   */
  findById(id: NotificationId): Promise<Notification | null>;

  /**
   * @description Finds a notification by its notificationId for deduplication
   * @param {string} notificationId - Notification ID generated by the service
   * @returns {Promise<Notification | null>} Notification entity or null if not found
   */
  findByNotificationId(notificationId: string): Promise<Notification | null>;

  /**
   * @description Finds a notification by event ID for idempotency
   * @param {string} eventId - EventBridge event ID
   * @returns {Promise<Notification | null>} Notification entity or null if not found
   */
  findByEventId(eventId: string): Promise<Notification | null>;

  /**
   * @description Creates a new notification record
   * @param {Notification} entity - Notification entity to persist
   * @returns {Promise<Notification>} Created notification entity
   */
  create(entity: Notification): Promise<Notification>;

  /**
   * @description Updates an existing notification
   * @param {NotificationId} id - Notification ID
   * @param {Partial<Notification>} patch - Partial notification data to update
   * @returns {Promise<Notification>} Updated notification entity
   */
  update(id: NotificationId, patch: Partial<Notification>): Promise<Notification>;

  /**
   * @description Lists notifications by specification with pagination
   * @param {NotificationSpec} spec - Query specification
   * @param {number} [limit] - Page size
   * @param {string} [cursor] - Optional pagination cursor
   * @returns {Promise<Page<Notification>>} Page of notifications
   */
  list(spec: NotificationSpec, limit?: number, cursor?: string): Promise<Page<Notification>>;

  /**
   * @description Finds pending notifications that need retry
   * @param {number} maxRetries - Maximum retry count
   * @param {number} [limit] - Maximum number of notifications to return
   * @returns {Promise<Notification[]>} Array of pending notifications
   */
  findPendingRetries(maxRetries: number, limit?: number): Promise<Notification[]>;

  /**
   * @description Counts notifications by specification
   * @param {NotificationSpec} [spec] - Query specification
   * @returns {Promise<number>} Total count
   */
  count(spec?: NotificationSpec): Promise<number>;
}

