version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - 'bash -lc "set -euo pipefail; echo Using Node: $(node -v); echo Using npm: $(npm -v)"'
      
  pre_build:
    commands:
      - 'echo Building signature-service...'
      - 'npm ci'
      - 'aws s3 cp s3://$CODE_BUCKET/shared-ts-layer.zip /tmp/shared-ts-layer.zip'
      - 'cd /tmp && unzip shared-ts-layer.zip'
      - 'echo "Layer contents:" && ls -la nodejs/'
      - 'echo "Dist contents:" && ls -la nodejs/dist/'
      - 'mkdir -p node_modules/@lawprotect'
      - 'cp -r nodejs/* node_modules/@lawprotect/shared-ts'
      - 'echo "Copied layer to:" && ls -la node_modules/@lawprotect/'
      - 'echo "Shared-ts contents:" && ls -la node_modules/@lawprotect/shared-ts/'
      - 'cd -'
      
  build:
    commands:
      - 'cd services/signature-service'
      - 'npm run test:unit:coverage'
      - 'npm run build'
      - 'npm prune --omit=dev'
      - |
        handlers=("create-envelope" "get-envelope" "send-envelope" "sign-document" "decline-signer" "share-document" "send-notification" "get-audit-trail" "get-envelopes-by-user" "update-envelope" "cancel-envelope" "download-document")
        for handler in "${handlers[@]}"; do
          echo "Creating sign-$handler.zip..."
          mkdir -p temp-$handler
          cp -r dist/handlers/$handler/* temp-$handler/
          cp package.json temp-$handler/
          cd temp-$handler && zip -r ../sign-$handler.zip . && cd ..
          rm -rf temp-$handler
        done

artifacts:
  files:
    - 'sign-*.zip'
