version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - |
        set -eu
        echo "[INFO] ===== Pre-build ====="

      # 1) Build packages/shared-ts (Prisma + build)
      - |
        echo "[INFO] Building packages/shared-ts"
        cd "$CODEBUILD_SRC_DIR/packages/shared-ts"
        npm ci
        export DATABASE_URL="${DATABASE_URL:-postgresql://user:pass@localhost:5432/postgres?schema=public}"
        npm run prisma:generate
        npm run build

      # 2) Instalar deps del servicio (con dev) para compilar y testear
      - |
        echo "[INFO] Installing deps in services/signature-service"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        npm ci

      # 3) Preparar Prisma client dentro del servicio
      - |
        echo "[INFO] Preparing Prisma client"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        if [ -d "$CODEBUILD_SRC_DIR/packages/shared-ts/prisma" ]; then
          mkdir -p prisma
          cp -r "$CODEBUILD_SRC_DIR/packages/shared-ts/prisma/"* prisma/
        fi
        export DATABASE_URL="${DATABASE_URL:-postgresql://user:pass@localhost:5432/postgres?schema=public}"
        npx -y prisma@5.22.0 generate
        node -e "try{require.resolve('@prisma/client');console.log('[OK] @prisma/client')}catch(e){console.error(e);process.exit(1)}"
        node -e "try{require.resolve('@lawprotect/shared-ts');console.log('[OK] @lawprotect/shared-ts')}catch(e){console.error(e);process.exit(1)}"

  build:
    commands:
      - |
        set -eu
        echo "[INFO] ===== Build & Package ====="

      # 4) Tests
      - |
        echo "[INFO] Running unit tests"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        export DATABASE_URL="${DATABASE_URL:-postgresql://user:pass@localhost:5432/postgres?schema=public}"
        npm run test:unit:coverage

      # 5) Build del servicio (ESM + CJS). Creamos tsconfig.cjs.json si no existe.
      - |
        echo "[INFO] Building service (ESM)"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        npm run build

        echo "[INFO] Ensuring tsconfig.cjs.json exists"
        if [ ! -f tsconfig.cjs.json ]; then
          cat > tsconfig.cjs.json << 'EOF'
          {
            "extends": "./tsconfig.json",
            "compilerOptions": {
              "module": "CommonJS",
              "outDir": "dist-cjs",
              "declaration": false,
              "esModuleInterop": true
            },
            "include": ["src/**/*"]
          }
          EOF
        fi

        echo "[INFO] Building service (CJS)"
        npx tsc -p tsconfig.cjs.json

      # 6) DEPS LAYER: construir en un folder limpio con prod deps (con fallback sin lockfile)
      - |
        echo "[INFO] Building dependencies layer (clean env)"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        rm -rf deps-build layer-deps sign-deps-layer.zip
        mkdir -p deps-build
        cp package.json deps-build/
        if [ -f package-lock.json ]; then cp package-lock.json deps-build/; fi
        cd deps-build
        if [ -f package-lock.json ]; then
          echo "[INFO] Using npm ci --omit=dev (lockfile present)"
          npm ci --omit=dev
        else
          echo "[WARN] package-lock.json not found. Using npm i --omit=dev"
          npm i --omit=dev
        fi
        test -d node_modules || { echo "[ERROR] node_modules not created for deps layer"; exit 1; }
        mkdir -p ../layer-deps/nodejs
        cp -r node_modules ../layer-deps/nodejs/
        cd ..
        (cd layer-deps && zip -qr ../sign-deps-layer.zip .)
        test -s sign-deps-layer.zip || { echo "[ERROR] sign-deps-layer.zip is empty"; exit 1; }
        rm -rf deps-build layer-deps
        echo "[INFO] Dependencies layer ZIP created"

      # 7) CORE LAYER: empaquetar **dist-cjs** como paquete CJS @lawprotect/sign-core
      - |
        echo "[INFO] Building core layer (CJS)"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        rm -rf layer-core sign-core-layer.zip
        mkdir -p "layer-core/nodejs/node_modules/@lawprotect/sign-core"
        cp -r "dist-cjs" "layer-core/nodejs/node_modules/@lawprotect/sign-core/dist"

        cat > "layer-core/nodejs/node_modules/@lawprotect/sign-core/package.json" << 'EOF'
        {
          "name": "@lawprotect/sign-core",
          "version": "1.0.0",
          "main": "index.js",
          "type": "commonjs"
        }
        EOF

        cat > "layer-core/nodejs/node_modules/@lawprotect/sign-core/index.js" << 'EOF'
        module.exports = {
          handlers: {
            createEnvelope: require('./dist/src/handlers/envelopes/CreateEnvelopeHandler').createEnvelopeHandler,
            getEnvelope: require('./dist/src/handlers/envelopes/GetEnvelopeHandler').getEnvelopeHandler,
            sendEnvelope: require('./dist/src/handlers/envelopes/SendEnvelopeHandler').sendEnvelopeHandler,
            updateEnvelope: require('./dist/src/handlers/envelopes/UpdateEnvelopeHandler').updateEnvelopeHandler,
            cancelEnvelope: require('./dist/src/handlers/envelopes/CancelEnvelopeHandler').cancelEnvelopeHandler,
            getEnvelopesByUser: require('./dist/src/handlers/envelopes/GetEnvelopesByUserHandler').getEnvelopesByUserHandler,
            downloadDocument: require('./dist/src/handlers/envelopes/DownloadDocumentHandler').downloadDocumentHandler,
            signDocument: require('./dist/src/handlers/signing/SignDocumentHandler').signDocumentHandler,
            declineSigner: require('./dist/src/handlers/signing/DeclineSignerHandler').declineSignerHandler,
            shareDocument: require('./dist/src/handlers/signing/ShareDocumentViewHandler').shareDocumentViewHandler,
            sendNotification: require('./dist/src/handlers/notifications/SendNotificationHandler').sendNotificationHandler,
            getAuditTrail: require('./dist/src/handlers/audit/GetAuditTrailHandler').getAuditTrailHandler
          }
        };
        EOF

        (cd layer-core && zip -qr ../sign-core-layer.zip .)
        test -s sign-core-layer.zip || { echo "[ERROR] sign-core-layer.zip is empty"; exit 1; }
        rm -rf layer-core
        echo "[INFO] Core layer ZIP created"

      # 8) ZIPs mínimos por Lambda (CommonJS)
      - |
        echo "[INFO] Creating minimal function ZIPs"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        make_zip () { echo "exports.handler = require('@lawprotect/sign-core').handlers.$2;" > index.js; zip -q "$1" index.js; rm index.js; }
        make_zip "sign-create-envelope.zip"       "createEnvelope"
        make_zip "sign-get-envelope.zip"          "getEnvelope"
        make_zip "sign-send-envelope.zip"         "sendEnvelope"
        make_zip "sign-sign-document.zip"         "signDocument"
        make_zip "sign-decline-signer.zip"        "declineSigner"
        make_zip "sign-share-document.zip"        "shareDocument"
        make_zip "sign-send-notification.zip"     "sendNotification"
        make_zip "sign-get-audit-trail.zip"       "getAuditTrail"
        make_zip "sign-get-envelopes-by-user.zip" "getEnvelopesByUser"
        make_zip "sign-update-envelope.zip"       "updateEnvelope"
        make_zip "sign-cancel-envelope.zip"       "cancelEnvelope"
        make_zip "sign-download-document.zip"     "downloadDocument"

      # 9) Subir y publicar layers (con fallback a última versión existente si falla publish)
      - |
        echo "[INFO] Uploading layers to S3 & publishing versions"
        set -e
        cd "$CODEBUILD_SRC_DIR/services/signature-service"

        if [ -z "${CODE_BUCKET:-}" ]; then
          echo "[ERROR] CODE_BUCKET not set"
          exit 1
        fi

        AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"

        aws s3 cp "sign-deps-layer.zip" "s3://$CODE_BUCKET/sign-deps-layer.zip"
        aws s3 cp "sign-core-layer.zip" "s3://$CODE_BUCKET/sign-core-layer.zip"

        get_latest_layer_arn () {
          local NAME="$1"
          aws lambda list-layer-versions --layer-name "$NAME" --max-items 1 --query "LayerVersions[0].LayerVersionArn" --output text 2>/dev/null || echo ""
        }

        publish_or_latest () {
          local NAME="$1"; local ZIP="$2"; local DESC="$3"
          local ARN=""
          set +e
          ARN=$(aws lambda publish-layer-version \
            --layer-name "$NAME" \
            --description "$DESC" \
            --zip-file "fileb://$ZIP" \
            --compatible-runtimes nodejs20.x \
            --query LayerVersionArn --output text 2>/dev/null)
          local RC=$?
          set -e
          if [ $RC -ne 0 ] || [ -z "$ARN" ] || [ "$ARN" = "None" ]; then
            echo "[WARN] publish-layer-version failed for $NAME, getting latest..."
            ARN="$(get_latest_layer_arn "$NAME")"
          fi
          echo "$ARN"
        }

        DEPS_LAYER_NAME="lawprotect365-sign-deps-stg"
        CORE_LAYER_NAME="lawprotect365-sign-core-stg"

        DEPS_LAYER_VERSION="$(publish_or_latest "$DEPS_LAYER_NAME" "sign-deps-layer.zip" "Signature service dependencies")"
        CORE_LAYER_VERSION="$(publish_or_latest "$CORE_LAYER_NAME" "sign-core-layer.zip" "Signature service core code")"

        echo "[INFO] Dependencies layer ARN: ${DEPS_LAYER_VERSION:-<empty>}"
        echo "[INFO] Core layer ARN:         ${CORE_LAYER_VERSION:-<empty>}"

        # Sanity list
        aws lambda list-layer-versions --layer-name "$CORE_LAYER_NAME" --max-items 5 || true
        aws lambda list-layer-versions --layer-name "$DEPS_LAYER_NAME" --max-items 5 || true

      # 10) Deploy de todas las Lambdas con 3 layers: shared + deps + core (solo ARNs no vacíos)
      - |
        echo "[INFO] Deploying Lambda functions"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"

        AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"
        SHARED_TS_LAYER_ARN="arn:aws:lambda:us-east-1:${AWS_ACCOUNT_ID}:layer:lawprotect365-shared-ts-layer-stg:1"

        build_layers_args () {
          local args="$SHARED_TS_LAYER_ARN"
          if [ -n "${DEPS_LAYER_VERSION:-}" ] && [ "${DEPS_LAYER_VERSION}" != "None" ]; then
            args="$args ${DEPS_LAYER_VERSION}"
          fi
          if [ -n "${CORE_LAYER_VERSION:-}" ] && [ "${CORE_LAYER_VERSION}" != "None" ]; then
            args="$args ${CORE_LAYER_VERSION}"
          fi
          echo "$args"
        }

        deploy_fn () {
          local FN="$1"; local ZIP="$2"
          local LAYERS_ARGS; LAYERS_ARGS="$(build_layers_args)"
          echo "[INFO] Deploying $FN"
          aws s3 cp "$ZIP" "s3://$CODE_BUCKET/$ZIP"
          aws lambda update-function-code --function-name "$FN" --s3-bucket "$CODE_BUCKET" --s3-key "$ZIP" >/dev/null
          aws lambda update-function-configuration --function-name "$FN" --layers $LAYERS_ARGS >/dev/null
          aws lambda wait function-updated --function-name "$FN"
        }

        deploy_fn "lawprotect365-sign-service-create-envelope-stg"        "sign-create-envelope.zip"
        deploy_fn "lawprotect365-sign-service-get-envelope-stg"           "sign-get-envelope.zip"
        deploy_fn "lawprotect365-sign-service-send-envelope-stg"          "sign-send-envelope.zip"
        deploy_fn "lawprotect365-sign-service-sign-document-stg"          "sign-sign-document.zip"
        deploy_fn "lawprotect365-sign-service-decline-signer-stg"         "sign-decline-signer.zip"
        deploy_fn "lawprotect365-sign-service-share-document-stg"         "sign-share-document.zip"
        deploy_fn "lawprotect365-sign-service-send-notification-stg"      "sign-send-notification.zip"
        deploy_fn "lawprotect365-sign-service-get-audit-trail-stg"        "sign-get-audit-trail.zip"
        deploy_fn "lawprotect365-sign-service-get-envelopes-by-user-stg"  "sign-get-envelopes-by-user.zip"
        deploy_fn "lawprotect365-sign-service-update-envelope-stg"        "sign-update-envelope.zip"
        deploy_fn "lawprotect365-sign-service-cancel-envelope-stg"        "sign-cancel-envelope.zip"
        deploy_fn "lawprotect365-sign-service-download-document-stg"      "sign-download-document.zip"

      # 11) appspec de cortesía
      - |
        echo "[INFO] Writing default appspec.yml"
        cd "$CODEBUILD_SRC_DIR/services/signature-service"
        cat > appspec.yml <<'EOF'
        version: 0.0
        Resources:
          - CreateEnvelope:
              Type: AWS::Lambda::Function
              Properties:
                Name: "lawprotect365-sign-service-create-envelope-stg"
                Alias: "live"
                CurrentVersion: 1
                TargetVersion: 1
        EOF

artifacts:
  files:
    - services/signature-service/sign-*.zip
    - services/signature-service/sign-deps-layer.zip
    - services/signature-service/sign-core-layer.zip
    - services/signature-service/appspec.yml
    - services/signature-service/appspec-*.yml
  discard-paths: yes
