version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - 'bash -lc "set -euo pipefail; echo Using Node: $(node -v); echo Using npm: $(npm -v)"'
      
  pre_build:
    commands:
      - 'echo "Build shared-ts first..."'
      - '[ -d "$CODEBUILD_SRC_DIR/packages/shared-ts" ] || { echo "shared-ts not found"; exit 2; }'
      - 'cd "$CODEBUILD_SRC_DIR/packages/shared-ts"'
      - 'pwd; ls -la'
      - 'npm ci'
      - 'DATABASE_URL="postgresql://user:pass@localhost:5432/postgres?schema=public" npx prisma generate'
      - 'npm run build'
      - 'cd "$CODEBUILD_SRC_DIR"'
      - 'echo "Install signature-service deps..."'
      - '[ -d "$CODEBUILD_SRC_DIR/services/signature-service" ] || { echo "signature-service not found"; exit 2; }'
      - 'cd "$CODEBUILD_SRC_DIR/services/signature-service"'
      - 'pwd; ls -la'
      - 'npm ci'
      - 'echo "Using Lambda layer for @lawprotect/shared-ts - no local symlink needed"'
      - 'npx prisma generate --schema ../../packages/shared-ts/prisma/schema.prisma'
      - 'echo "Verifying prisma client..."'
      - 'ls -la node_modules/@prisma/client/'
      
  build:
    commands:
      - 'cd "$CODEBUILD_SRC_DIR/services/signature-service"'
      - 'npm run test:unit:coverage'
      - 'npm run build'
      - 'npm prune --omit=dev'
      - 'rm -rf node_modules/@lawprotect/shared-ts'
      - 'echo "Runtime will use Lambda layer for @lawprotect/shared-ts"'
      - |
        handlers=("create-envelope" "get-envelope" "send-envelope" "sign-document" "decline-signer" "share-document" "send-notification" "get-audit-trail" "get-envelopes-by-user" "update-envelope" "cancel-envelope" "download-document")
        for handler in "${handlers[@]}"; do
          echo "Packaging sign-$handler.zip"
          mkdir -p temp-$handler
          cp -r dist/handlers/$handler/* temp-$handler/
          cp package.json temp-$handler/
          (cd temp-$handler && zip -r ../sign-$handler.zip .)
          rm -rf temp-$handler
        done

artifacts:
  files:
    - 'services/signature-service/sign-*.zip'
  discard-paths: yes