version: '3.8'

services:
  localstack:
    container_name: lawprotect365-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      # Services to enable (excluding dynamodb since we use DynamoDB Local)
      - SERVICES=s3,kms,cognito-idp,eventbridge,ssm
      
      # Persistence
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      
      # AWS credentials for LocalStack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      
      # DynamoDB configuration (disabled since we use DynamoDB Local)
      # - DYNAMODB_SHARE_DB=1
      # - DYNAMODB_IN_MEMORY=1
      
      # S3 configuration
      - S3_SKIP_SIGNATURE_VALIDATION=1
      
      # KMS configuration
      - KMS_PROVIDER=local-kms
      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/tmp/localstack"
    networks:
      - localstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  localstack-network:
    driver: bridge
